name: Build TurboPFor

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      ref:
        description: TurboPFor repo ref
        required: true
        default: master
        type: string
      create-pr:
        description: Create a pull request
        default: false
        type: boolean

permissions:
  contents: write
  pull-requests: write

env:
  RETENTION: 7

jobs:
  build-linux:
    name: Linux build
    strategy:
      matrix:
        arch: [arm64, x64]
    runs-on: ${{ matrix.arch == 'arm64' && 'ubuntu-22.04-arm' || 'ubuntu-22.04' }}
    steps:
      - name: Check out TurboPFor repository
        uses: actions/checkout@v5
        with:
          repository: powturbo/TurboPFor-Integer-Compression
          ref: ${{ github.event.inputs.ref }}

      - name: Build
        run: make libic.so

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: linux-${{ matrix.arch }}
          path: libic.so
          retention-days: ${{ env.RETENTION }}
          if-no-files-found: error

  build-macos:
    name: macOS build
    strategy:
      matrix:
        arch: [arm64, x64]
    runs-on: macos-latest
    env:
      ARCH: ${{ matrix.arch == 'arm64' && 'arm64' || 'x86_64' }}
    steps:
      - name: Check out TurboPFor repository
        uses: actions/checkout@v5
        with:
          repository: powturbo/TurboPFor-Integer-Compression
          ref: ${{ github.event.inputs.ref }}

      - name: Build
        run: make libic.so

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: osx-${{ matrix.arch }}
          path: libic.so
          retention-days: ${{ env.RETENTION }}
          if-no-files-found: error

  build-windows:
    name: Windows build
    strategy:
      matrix:
        arch: [arm64, x64]
    runs-on: ${{ matrix.arch == 'arm64' && 'windows-11-arm' || 'windows-2022' }}
    steps:
      - name: Check out TurboPFor repository
        uses: actions/checkout@v5
        with:
          repository: powturbo/TurboPFor-Integer-Compression
          ref: ${{ github.event.inputs.ref }}
          path: turbopfor

      - name: Check out turbopfor-bindings repository
        uses: actions/checkout@v5
        with:
          path: bindings

      - name: Patch Makefile
        working-directory: turbopfor
        run: git apply ../bindings/makefile.patch

      - name: Build
        working-directory: turbopfor
        run: |
          make ic.dll

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: win-${{ matrix.arch }}
          path: turbopfor/ic.dll
          retention-days: ${{ env.RETENTION }}
          if-no-files-found: error

  create-pr:
    name: Create a pull request
    needs: [build-linux, build-macos, build-windows]
    if: github.event.inputs.create-pr == 'true'
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v5

      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          path: src/Nethermind.TurboPFor/runtimes

      - name: Move artifacts
        working-directory: src/Nethermind.TurboPFor/runtimes
        run: |
          mv -f linux-arm64/libic.so linux-arm64/native/libic.so
          mv -f linux-x64/libic.so linux-x64/native/libic.so
          mv -f osx-arm64/libic.dylib osx-arm64/native/libic.dylib
          mv -f osx-x64/libic.dylib osx-x64/native/libic.dylib
          mv -f win-arm64/ic.dll win-arm64/native/ic.dll
          mv -f win-x64/ic.dll win-x64/native/ic.dll

      - name: Create a pull request
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          head_branch=feature/mcl-build-$GITHUB_RUN_NUMBER-$GITHUB_RUN_ATTEMPT
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"
          git checkout -b $head_branch
          git add -A
          git commit -am "Update TurboPFor binaries"
          git push origin $head_branch
          gh pr create -B $GITHUB_REF_NAME -H $head_branch -t "Update TurboPFor binaries" -b "Built and updated TurboPFor binaries"
