name: Test / Publish

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]
  release:
    types: [published]
  workflow_dispatch:
    inputs:
      publish:
        description: Publish to NuGet
        default: 'No'
        type: choice
        options:
          - 'No'
          - Staging
          - Production

jobs:
  test:
    name: Test
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - ubuntu-24.04-arm
          - macos-latest
          - macos-15-intel
          - windows-latest
    runs-on: ${{ matrix.os }}
    steps:
      - name: Check out repository
        uses: actions/checkout@v7
        with:
          lfs: true

      - name: Set up .NET
        uses: actions/setup-dotnet@v6

      - name: Test
        working-directory: src/Nethermind.TurboPForBindings.Tests
        run: dotnet run -c release

  publish:
    name: Publish
    needs: test
    if: github.event_name == 'workflow_dispatch' && inputs.publish != 'No' || github.event_name == 'release'
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    env:
      NUGET_HOST: ${{ inputs.publish == 'Staging' && 'https://int.nugettest.org' || 'https://www.nuget.org' }}
    steps:
      - name: Check out repository
        uses: actions/checkout@v7
        with:
          lfs: true

      - name: Set up .NET
        uses: actions/setup-dotnet@v6

      - name: NuGet login
        uses: nuget/login@v1
        id: login
        with:
          user: ${{ secrets.NUGET_USER }}
          audience: ${{ env.NUGET_HOST }}
          token-service-url: ${{ env.NUGET_HOST }}/api/v2/token

      - name: Publish
        working-directory: src
        run: |
          dotnet pack ./Nethermind.TurboPForBindings -c release
          dotnet nuget push ./artifacts/package/release/*.nupkg \
            -k "${{ steps.login.outputs.NUGET_API_KEY }}" -s ${{ env.NUGET_HOST }}/api/v2/package
