name: Test / Publish

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]
  release:
    types: [published]
  workflow_dispatch:
    inputs:
      publish:
        description: Publish to NuGet
        default: None
        type: choice
        options:
          - "No"
          - Staging
          - Production

jobs:
  test:
    name: Test
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - ubuntu-24.04-arm
          - macos-latest
          - macos-13
          - windows-latest
    runs-on: ${{ matrix.os }}
    steps:
      - name: Check out repository
        uses: actions/checkout@v5
        with:
          lfs: true

      - name: Set up .NET
        uses: actions/setup-dotnet@v5

      - name: Test
        working-directory: src/Nethermind.TurboPFor.Tests
        run: dotnet run -c release

  publish:
    name: Publish
    needs: test
    if: github.event_name == 'workflow_dispatch' && github.event.inputs.publish != 'No' || github.event_name == 'release'
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v5
        with:
          lfs: true

      - name: Set up .NET
        uses: actions/setup-dotnet@v5

      - name: Publish
        working-directory: src
        run: |
          dotnet pack ./Nethermind.TurboPFor -c release
          dotnet nuget push ./artifacts/package/release/*.nupkg \
            -k ${{ github.event.inputs.publish == 'Staging' && secrets.NUGETTEST_API_KEY || secrets.NUGET_API_KEY }} \
            -s ${{ github.event.inputs.publish == 'Staging' && 'https://apiint.nugettest.org/v3/index.json' || 'https://api.nuget.org/v3/index.json' }}
